<?php


/**
 * Implements hook_theme().
 */
function crl_provider_theme() {
  $hooks = array(
    // Theme hook to generate a resource teaser (used in views rows). This will
    // automatically get used by views based on its name and the standard
    // template suggestion rules. We must formally declare it to ensure our
    // custom preprocess functions get used, etc.
    'views_view_fields__provider_lists' => array(
      'variables' => array(),
      'template' => 'views-view-fields--provider-lists',
    ),
  );
  foreach ($hooks as &$hook) {
    // Make sure that our actual theme hooks and/or preprocessor logic is
    // included for each entry.
    $hook['path'] = drupal_get_path('module', 'crl_provider') . '/themes';
    $hook['file'] = 'crl_provider.theme.inc';
  }
  return $hooks;
}


/**
 * Implements hook_block_info().
 */
function crl_provider_block_info() {
  // The resource summary is a block at the top of each resource.
  $blocks['crl_provider_summary'] = array(
    'info' => t('CRL Provider Summary'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  // The "back to index" block shows a caclulated back link for navigation.
  $blocks['crl_provider_back_to_index'] = array(
    'info' => t('CRL Provider to Index'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function crl_provider_block_view($delta = '') {
  // Lazy-load our block build methods via an object.
  static $blocks;
  if (!is_object($blocks)) {
    $blocks = new CrlProviderBlocks();
  }
  return $blocks->buildBlock($delta);
}