; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.30"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta5"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[coder][subdir] = "contrib"
projects[coder][version] = "1.2"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[context][subdir] = "contrib_patched"
projects[context][version] = "3.2"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[dynamic_cache][subdir] = "contrib"
projects[dynamic_cache][version] = "1.0-rc2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[escape_admin][subdir] = "contrib"
projects[escape_admin][version] = "1.1"

projects[extlink][subdir] = "contrib"
projects[extlink][version] = "1.18"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[fivestar][subdir] = "contrib_patched"
projects[fivestar][version] = "2.1"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.5"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"

projects[hide_formats][subdir] = "contrib"
projects[hide_formats][version] = "1.1"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.9"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jump_menu][subdir] = "contrib"
projects[jump_menu][version] = "1.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[linkchecker][subdir] = "contrib"
projects[linkchecker][version] = "1.2"

projects[mail_logger][subdir] = "contrib"
projects[mail_logger][version] = "1.x-dev"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc7"

projects[message][subdir] = "contrib"
projects[message][version] = "1.9"

projects[message_digest][subdir] = "contrib"
projects[message_digest][version] = "1.0"

projects[message_notify][subdir] = "contrib"
projects[message_notify][version] = "2.5"

projects[message_ui][subdir] = "contrib"
projects[message_ui][version] = "1.4"

projects[message_subscribe][subdir] = "contrib"
projects[message_subscribe][version] = "1.0-rc2"

projects[message_subscribe_email_frequency][subdir] = "contrib"
projects[message_subscribe_email_frequency][version] = "1.0"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.0-beta3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[pathologic][subdir] = "contrib"
projects[pathologic][version] = "2.12"

projects[print][subdir] = "contrib"
projects[print][version] = "1.3"

projects[punctuation_preprocessor][subdir] = "contrib"
projects[punctuation_preprocessor][version] = "1.0"

projects[rate][subdir] = "contrib_patched"
projects[rate][version] = "1.7"

projects[realname][subdir] = "contrib"
projects[realname][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[revisioning][subdir] = "contrib"
projects[revisioning][version] = "1.9"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.13"

projects[search_api_db][subdir] = "contrib"
projects[search_api_db][version] = "1.3"

projects[search_api_saved_searches][subdir] = "contrib_patched"
projects[search_api_saved_searches][version] = "1.3"

projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][version] = "1.5"

projects[stringoverrides][subdir] = "contrib"
projects[stringoverrides][version] = "1.8"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[tablefield][subdir] = "contrib_patched"
projects[tablefield][version] = "2.2"

projects[taxonomy_access][subdir] = "contrib_patched"
projects[taxonomy_access][version] = "1.0-rc1"

projects[taxonomy_display][subdir] = "contrib"
projects[taxonomy_display][version] = "1.1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[viewfield][subdir] = "contrib_patched"
projects[viewfield][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta7"

projects[voting_rules][subdir] = "contrib"
projects[voting_rules][version] = "1.0-alpha1"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.11"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.20"

projects[wysiwyg][subdir] = "contrib_patched"
projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][version] = "3.1"

; Modules
projects[crl_access_by_ip][type] = "module"
projects[crl_access_by_ip][download][type] = "git"
projects[crl_access_by_ip][download][url] = "git@github.com:crlsystems/crl-drupal-access-by-ip.git"
projects[crl_access_by_ip][download][branch] = "master-7"
projects[crl_access_by_ip][download][revision] = "c2a580e7473aed644d2385a38bd0be219db12d2e"

projects[crl_edesiderata][type] = "module"
projects[crl_edesiderata][download][type] = "git"
projects[crl_edesiderata][download][url] = "git@github.com:crlsystems/crl-drupal-edesiderata.git"
projects[crl_edesiderata][download][branch] = "develop"
projects[crl_edesiderata][download][revision] = "68e7c231497459a75717b22423e384b28c29713f"

projects[crl_user][type] = "module"
projects[crl_user][download][type] = "git"
projects[crl_user][download][url] = "git@github.com:crlsystems/crl-drupal-user.git"
projects[crl_user][download][revision] = "01315f8981dc2e5ff5d6ba2a3ced7bb2e9fddc9f"

projects[crowd][type] = "module"
projects[crowd][download][type] = "git"
projects[crowd][download][url] = "rjacobs@git.drupal.org:project/crowd.git"
projects[crowd][download][branch] = "7.x-2.x"
projects[crowd][download][revision] = "c329e1b918d11d031bd224220cac2b5c58ddea65"

projects[crowd_provisioning][type] = "module"
projects[crowd_provisioning][download][type] = "git"
projects[crowd_provisioning][download][url] = "rjacobs@git.drupal.org:sandbox/rjacobs/1980720.git"
projects[crowd_provisioning][download][branch] = "7.x-1.x"
projects[crowd_provisioning][download][revision] = "7a906529e173deb59b9737aff1d54efe73ea62b7"

projects[salesforce_unsupported][type] = "module"
projects[salesforce_unsupported][download][type] = "git"
projects[salesforce_unsupported][download][url] = "http://git.drupal.org/project/salesforce.git"
projects[salesforce_unsupported][download][branch] = "7.x-2.x"
projects[salesforce_unsupported][download][revision] = "4618f0ce8ffaa975df7ff8a8afb294fe876c4919"

; Themes
projects[crl][type] = "theme"
projects[crl][download][type] = "git"
projects[crl][download][url] = "git@github.com:crlsystems/crl-drupal-edesiderata-theme.git"
projects[crl][download][revision] = "ccd68e8b3c97fe3b3d32dd9a973a60761e712f48"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[devbart][download][type] = ""
projects[devbart][download][url] = ""
projects[devbart][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[salesforce][download][type] = ""
libraries[salesforce][download][url] = ""
libraries[salesforce][directory_name] = "salesforce"
libraries[salesforce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

