<?php

/**
 * @file
 * Install, update and uninstall functions for the crl_helpers module.
 */


/**
 * Set custom allowed values function for field_institution.
 * 
 * This handleing has been moved to crl_user, but we keep the record here to
 * ensure hook_update_n counts are consistent.
 */
function crl_helpers_update_7100() {
  // Set oplist function for field_institution.
  // crl_helpers_set_oplist_function('field_institution', 'crl_helpers_inst_oplist');
}
